language: node_js
node_js:
  - "10"
install: npm install discord.js typedoc typescript @types/node
jobs:
  include:
    - stage: deploy
      script: bash ./scripts/travis.sh
cache:
  directories:
    - node_modules